MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]

  resources :bands, only: [:index, :create, :new, :edit, :show, :update, :destroy]
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

#  ActiveRecord::Base instance methods that run validations:
  #create
  #create!
  #save
  #save!
  #update
  #update_attributes
  #update_attributes!

  #User.find_by(key: value)
    #is a class method that allows you to search by key-value pair

  validates :email, presence: true, uniqueness: true
  validates :password_digest,  presence: true, uniqueness: true
  validates :password,  length: { minimum: 8, allow_nil: true }
  validates :session_token,  presence: true, uniqueness: true

  has_many  :bands,
    primary_key: :id,
    foreign_key:  :user_id, 
    class_name: :Band

  after_initialize  :ensure_session_token
    #sets session_token before validation if it's not present

  attr_reader :password

  # F => self.find_by_credentials(username, password)
  # R => reset_session_token!
  # I => is_password?(password)
  # P => password=(password)
  # private
  # E => ensure_session_token
  # G => self.generate_session_token


  def self.find_by_credentials(e_mail, password)
    #First, find user by username/email, save as variable
    # return user if found
    # && password matches!!
    # else, return nil
    user = User.find_by(email: e_mail)
    return nil unless user && user.is_password?(password)
    user
  end

  def reset_session_token!
    # resets session_token each time user logs in
    self.session_token = SecureRandom::urlsafe_base64
    # remember to SAVE user's session_token attribute!
    self.save!
    # return this new session_token
    self.session_token
  end

  def is_password?(password)
    #generate a BCrypted_password from the user's password_digest
    b_crypt_password = BCrypt::Password.new(self.password_digest)
    #check if the b_crypted_password matches user's inputted password
    b_crypt_password.is_password?(password)
                  # |^ this is bcrypt::password's "is_password?" method
  end

  def password=(password)
    #create an password instance for this user
    # create a corresponding password_digest for user by BCrypting it
    @password = password
    self.password_digest = BCrypt::Password.create(password)
    #self._____= calls a setter method defined for us by ActiveRecord
      # which is the state saved by self.save
  end

  private

  #ensure_session_token to be used "after_initialize"
  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def ensure_session_token
    # uses self.session_token OR
    # self.session_token is_now = self.class.generate_session_token
    self.session_token ||= self.class.generate_session_token
  end


end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new # <= ?
    render :new
    #tells controller to render the new.html.erb template for users
  end

  def create
    @user = User.new(user_params)

    if @user.save # <= if user passes validations (i.e., enters valid email and password)
    # log-in user! => resets the user's session_token and cookie
      # session[:session_token] = user.reset_session_token!
      log_in_user!(@user)
    # redirect user to where you see fit - usually the user's homepage
      redirect_to user_url(@user.id)
        # user_url takes an argument - the wildcard, user's id
        # which can be accessed with both @user or @user.id
    else # if user does not successfully create an account
      # display errors (e.g., "email can't be blank")
      flash.now[:errors] = @user.errors.full_messages
      # flash.now[:errors] = ['invalid email/password']
      # errors.full_messages is an array of strings, if no errors, then it's an empty [] => nil
      # use flash instead of flash.now when READING errors, flash.now for SETTING

      # re-display new log-in
      render :new
    end
  end

  def show
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
    # permit :email and :password as the parameters required for user to log-in
  end
end

MusicApp/app/views/users/new.html.erb
<h2> Greetings </h2>

<form class="forms" action="<%= users_url %>" method="post">
<%- #references to urls should always be in printed erb tags -%>
<%- #the post method above posts the newly created user to the page of all users -%>
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token %>">
<%- #the form_authenticity_token should always be in unprinted erb tags -%>
<%- #Make sure there is NO SPACE! The form_authenticity_token returns a string. -%>
<%- #if there are any spaces, it won't match the authenticity token -%>
  <label for="user_email">Email: </label>
  <input id="user_email" type="text" name="user[email]" value="">

<br/>
  <label for="user_password">Password: </label>
  <input id="user_pssword" type="password" name="user[password]" value="">

<br/>
  <input type="submit" name="" value="Sign up">


</form>

MusicApp/app/views/users/show.html.erb
<h1>Hi <%= current_user.email %>, welcome to your profile page!</h1>

<br/>

<h2>Click the button below to add a band</h2>
<form action="<%= new_band_url %>" method="get">
  <label for="adding_band"></label>
  <input id="add_band" type="submit" name="" value="Add Band">

<h2>Here are your bands. Click "See Band" to see more information about your band. </h2>
  <% current_user.bands.each do |band| %>
      <%= band.name %>
    <form action="<%=band_url%>" method="get">
      <label for="see_band"></label>
      <input id="see_band" type="submit" name="" value="See Band">
    </form>
  <% end %>